---
stages:
  - rubocop
  - foodcritic
  - chefspec
  - kitchen

rubocop:
  stage: rubocop
  script:
    - rake rubocop

foodcritic:
  stage: foodcritic
  script:
    - rake foodcritic

chefspec:
  stage: chefspec
  script:
    - rake chefspec
  allow_failure: true

.kitchen:
  stage: kitchen
  resource_group: $CI_JOB_NAME-$CI_PROJECT_NAME
  script:
    - sleep $((RANDOM%30))
    - kitchen test $SUITE-$PLATFORM
  after_script:
    # make sure failed runs are cleaned up too:
    - kitchen destroy $SUITE-$PLATFORM
  parallel:
    matrix:
      - SUITE:
        # - accounts
        # - apt
        # - autofs
        # - banner
        # - chef
        # - fail2ban
        # - ferm
        # - linuxlogo
        # - mail
        # - multipath
        # - nftables
        # - nsswitch
        # - ohai
        # - resolv
        # - rsyslog
        # - snmp
        # - ssh
        - ssl
        # - sudo
        # - systemd
        # - time
        # - x509

# circumvent limit of 50 parallel jobs:
stretch:
  extends: .kitchen
  variables:
    PLATFORM: stretch
  allow_failure: true # Stretch vagrant images are currently broken

buster:
  extends: .kitchen
  variables:
    PLATFORM: buster

bullseye:
  extends: .kitchen
  variables:
    PLATFORM: bullseye

.post:
   script:
    - kitchen destroy
