---
stages:
  - rubocop
  - foodcritic
  - chefspec
  - kitchen

rubocop:
  stage: rubocop
  script:
    - rake rubocop

foodcritic:
  stage: foodcritic
  script:
    - rake foodcritic

chefspec:
  stage: chefspec
  script:
    - rake chefspec
  allow_failure: true

kitchen:
  stage: kitchen
  resource_group: $CI_JOB_NAME-$CI_PROJECT_NAME
  script:
    - kitchen test $SUITE-$PLATFORM
  after_script:
    # make sure failed runs are cleaned up too:
    - kitchen destroy $SUITE-$PLATFORM
  parallel:
    matrix:
      - PLATFORM:
        - bullseye
        SUITE:
        - accounts
        - apt
        - autofs
        - banner
        - chef
        - ferm
        - linuxlogo
        - mail
        - multipath
        - nftables
        - nsswitch
        - ohai
        - resolv
        - snmp
        - ssh
        - ssl
        - sudo
        - systemd
        - time
        - x509

.post:
   script:
    - kitchen destroy
