---
stages:
  - lint
  - chefspec
  - kitchen

rubocop:
  stage: lint
  tags:
    - rubocop
  script:
    - rake rubocop

foodcritic:
  stage: lint
  tags:
    - foodcritic
  script:
    - rake foodcritic
  allow_failure: true

cookstyle:
  stage: lint
  tags:
    - cookstyle
  script:
    - cookstyle --fail-level E -f junit --out cookstyle.xml
  artifacts:
    when: always
    paths:
      - cookstyle.xml
    reports:
      junit: cookstyle.xml

chefspec:
  stage: chefspec
  script:
    - rake chefspec
  allow_failure: true

.kitchen:
  stage: kitchen
  resource_group: $CI_JOB_NAME-$CI_PROJECT_NAME
  script:
    - sleep $((RANDOM%30))
    - kitchen create $SUITE-$PLATFORM
    - kitchen converge $SUITE-$PLATFORM
    - kitchen verify $SUITE-$PLATFORM
  after_script:
    # make sure failed runs are always cleaned up too:
    - kitchen destroy $SUITE-$PLATFORM
  parallel:
    matrix:
      - SUITE:
        - accounts
        - apt
        - autofs
        - banner
        - chef
        - fail2ban
        - ferm
        - linuxlogo
        - mail
        - multipath
        - nftables
        - nsswitch
        - ohai
        - resolv
        - rsyslog
        - snmp
        - ssh
        - ssl
        - sudo
        - systemd
        - time
        - x509

# circumvent limit of 50 parallel jobs:
buster:
  extends: .kitchen
  variables:
    PLATFORM: buster
  tags:
    - kitchen
    - buster

rh7:
  extends: .kitchen
  variables:
    PLATFORM: rh7

rh8:
  extends: .kitchen
  variables:
    PLATFORM: rh8

rh9:
  extends: .kitchen
  variables:
    PLATFORM: rh9

.post:
   script:
    - kitchen destroy
