---
stages:
  - rubocop
  - foodcritic
  - chefspec
  - kitchen

rubocop:
  stage: rubocop
  script:
    - rake rubocop

foodcritic:
  stage: foodcritic
  script:
    - rake foodcritic

chefspec:
  stage: chefspec
  script:
    - rake chefspec
  allow_failure: true

.kitchen:
  stage: kitchen
  resource_group: $CI_JOB_NAME-$CI_PROJECT_NAME
  script:
    - sleep $((RANDOM%30))
    - kitchen test $SUITE-$PLATFORM
  after_script:
    # make sure failed runs are cleaned up too:
    - kitchen destroy $SUITE-$PLATFORM
  parallel:
    matrix:
      - SUITE:
        - accounts
        - apt
        - autofs
        - banner
        - chef
        - fail2ban
        - ferm
        - linuxlogo
        - mail
        - multipath
        - nftables
        - nsswitch
        - ohai
        - resolv
        - snmp
        - ssh
        - ssl
        - sudo
        - systemd
        - time
        - x509

# circumvent limit of 50 parallel jobs:
buster:
  extends: .kitchen
  variables:
    PLATFORM: buster

centos7:
  extends: .kitchen
  variables:
    PLATFORM: centos7

centos8:
  extends: .kitchen
  variables:
    PLATFORM: centos8

.post:
   script:
    - kitchen destroy
