---
driver:
  name: docker
  privileged: true
  provision_command:
    # https://github.com/test-kitchen/kitchen-docker/issues/285:
    - mkdir -p /run/sshd
    - apt-get -y install chef || true
  require_chef_omnibus: false

platforms:
  - name: debian-stretch
  - name: debian-jessie
  - name: debian-wheezy
  - name: debian-buster
    # chef package removed from testing as of 2018-04-21
    driver:
      require_chef_omnibus: true
  - name: ubuntu-16.04
  - name: centos-7
    driver:
      require_chef_omnibus: true
