---
driver:
  name: docker
  privileged: true

# platforms:
# - name: ubuntu-14.04
#   run_list: recipe[apt]
# - name: centos-6.6

suites:
  - name: accounts
    run_list:
      - recipe[sys::accounts]
    attributes:
