---
driver:
  name: docker
  privileged: true
  # https://github.com/test-kitchen/kitchen-docker/issues/285:
  provision_command: mkdir -p /run/sshd

platforms:
  - name: debian-buster
  - name: debian-stretch
  - name: debian-jessie
  - name: debian-wheezy
  - name: ubuntu-16.04
  - name: centos-7
