---
driver:
  name: docker
  privileged: true

platforms:
 - name: debian-unstable
 - name: debian-stretch
 - name: debian-jessie
 - name: debian-wheezy
 - name: ubuntu-16.04
 - name: centos-7

suites:
  - name: accounts
    run_list:
      - recipe[sys::accounts]
    attributes:
