---
driver:
  name: vagrant
  box_check_update: true

provisioner:
  require_chef_omnibus: false
  install_strategy: skip
  log_level: warn
  # name: chef-solo
  # chef_solo_path: /usr/bin/chef-solo
  name: chef_zero
  chef_client_path: /usr/bin/chef-client
  data_bags_path: test/integration/data_bags

verifier:
  name: busser
  ruby_bindir: /usr/bin

platforms:
  - name: stretch
    driver:
      box: debian/stretch64
      provider: libvirt
      provision: true
      vagrantfiles:
        - vagrant.rb
  - name: jessie
    driver:
      box: debian/jessie64
      require_chef_omnibus: 12.0.3
      provider: libvirt
      provision: true
      vagrantfiles:
        - vagrant.rb
  - name: buster
    driver:
      box: gsi/buster64
      provider: libvirt
      provision: true
      vagrantfiles:
        - vagrant.rb
  - name: xenial
    driver:
      box: generic/ubuntu1604
      provider: libvirt
      provision: true
      vagrantfiles:
        - vagrant.rb

suites:
  - name: sys_accounts
    run_list:
      - recipe[sys::accounts]
    attributes:
      sys:
        accounts:
          homer:  # empty
          bart:   # databag
          lisa:
            home: /home/lisa
            gid: simpsons
          root:
            # existing account, password should be changed,
            #  otherwise left untouched
            password: "$6$aycaramba$ql7zzi/ASEyEA.MsG5/7I6njGIfXoOn.JJjbToCLfadhYa9axBSJ.bWJiALYy3vA1FnzPx.ycq0uCXqOFrgW6/"
        groups:
          simpsons:
  - name: sys_autofs
    run_list:
      - recipe[sys::autofs]
      - recipe[sys::file]
    attributes:
      sys:
        autofs:
          maps:
            /test:
              map: /etc/autofs.test
        file:
          # create a bind mount autofs map for testing
          /etc/autofs.test:
            content: tempo -fstype=bind :/tmp
            notifies:
              - reload
              - service[autofs]
  - name: sys_mail
    run_list:
      - recipe[sys::mail]
    attributes:
      sys:
        mail:
          relay:
            smtp.example.com
          aliases:
            array:
              - '| /bin/true'
              - /tmp/mail.test
