---
driver:
  name: docker
  privileged: true
  provision_command:
    # https://github.com/test-kitchen/kitchen-docker/issues/285:
    - mkdir -p /run/sshd
    - apt-get -q -y install chef || true
    - apt-get -q -y install exim4-base || true
  require_chef_omnibus: false

provisioner:
  log_level: warn

platforms:
  - name: debian-stretch
  - name: debian-jessie
  - name: debian-wheezy
    # wheezy chef package is 10.12
    driver:
      require_chef_omnibus: 12.0.3
  - name: debian-buster
  - name: debian-bullseye
  - name: ubuntu-18.04
  - name: centos-7
    driver:
      require_chef_omnibus: 12
      provision_command:
        - yum install -y rubygems
