---
driver:
  name: docker
  privileged: true
  # https://github.com/test-kitchen/kitchen-docker/issues/285:
  provision_command: mkdir -p /run/sshd

platforms:
 - name: debian-unstable
 - name: debian-stretch
 - name: debian-jessie
 - name: debian-wheezy
 - name: ubuntu-16.04
 - name: centos-7

suites:
  - name: accounts
    run_list:
      - recipe[sys::accounts]
    attributes:
