AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Style/AlignHash:
  EnforcedHashRocketStyle: table

# Don't force [] instead of Array.new etc.
Style/EmptyLiteral:
  Enabled: false

Style/ExtraSpacing:
  ForceEqualSignAlignment: true

# don't enforce {key: value, ...}
Style/HashSyntax:
  Enabled: false

# Don't check for double quotes vs single quotes for now:
Style/StringLiterals:
  Enabled: false
