language: ruby
cache: bundler

sudo: required
dist: trusty

services: docker

# bundler in the travis image is too old:
before_install:
    - gem install bundler

bundler_args: --without plugins

install:
  # chefspec requires that the repo is checked out to a dir
  #  named like the cookbook name, therefore we check it out again
  #  cf. https://stackoverflow.com/questions/32580821/
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git sys
  - cd sys
  - git checkout -qf $TRAVIS_COMMIT
  - bundle install --without plugins

env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.docker.yml

matrix:
  include:
    # sys LWRPs for now not compatible with Chef 13
    - env: CHEF_VERSION=13
      rvm: ruby-head
    - env: CHEF_VERSION=12.14.60
      rvm: 2.3.1
    - env: CHEF_VERSION=12.3.0
      rvm: 2.1.5
    - env: CHEF_VERSION=12.0.3
      rvm: 2.1.5

jobs:
  include:
    - stage: rubocop
      script: bundle exec rake rubocop
    - stage: foodcritic
      script: bundle exec rake foodcritic
    - stage: chefspec
      script: bundle exec rake chefspec
    - stage: kitchen
      script: bundle exec rake kitchen:all
