---
language: ruby
cache: bundler

sudo: required
dist: trusty

services: docker

# bundler in the travis image is too old:
before_install:
  - gem install bundler

bundler_args: --without plugins

install:
  # chefspec requires that the repo is checked out to a dir
  #  named like the cookbook name, therefore we check it out again
  #  cf. https://stackoverflow.com/questions/32580821/
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git sys
  - cd sys
  - git checkout -qf $TRAVIS_COMMIT
  - bundle install --without plugins

env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.docker.yml
  matrix:
    - CHEF_VERSION=12
    - CHEF_VERSION=12.3
    - CHEF_VERSION=13
    - CHEF_VERSION=14
    - CHEF_VERSION=11

rvm:
  - 2.3
  - 2.4
  - 2.1
  - 1.9

# cf. https://travis-ci.com/chuhn/chef-install-test/
matrix:
  exclude:
    - rvm: 1.9
      env: CHEF_VERSION=12
  allow_failures:
    - rvm: 2.4
    - rvm: 1.9
    - env: CHEF_VERSION=14
    - env: CHEF_VERSION=13
      env: CHEF_VERSION=11

stages:
  - rubocop
  - foodcritic
  - test
  - kitchen

# this is the script for the test stage, where the matrix is expanded
script: bundle exec rake chefspec

jobs:
  include:
    - stage: rubocop
      script: bundle exec rake rubocop
    - stage: foodcritic
      script: bundle exec rake foodcritic
    - stage: kitchen
      script: bundle exec rake kitchen:all
