---
language: ruby
cache: bundler

dist: xenial

services: docker

# bundler in the travis image is too old:
before_install:
  - gem install bundler

bundler_args: --without vagrant

before_script:
  # integration test for sys::autofs will start automounter
  #  this will fail inside docker container because autofs4 cannot be loaded
  #  pre-loading autofs4 on the host fixes this issue
  - sudo modprobe autofs4
  - bundle exec kitchen list

env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.docker.yml

rvm:
# - system # does not work with `gem install bundler`
  - 2.3
  - 2.5
# - 2.1
#     before_install:
#        - gem install bundler -v ‘< 2’

stages:
  - rubocop
  - foodcritic
  - chefspec
  - kitchen

jobs:
  fast_finish: true
  include:
    - stage: rubocop
      script: bundle exec rake rubocop
    - stage: foodcritic
      script: bundle exec rake foodcritic
    - stage: chefspec
      script: bundle exec rake chefspec
      env: CHEF_VERSION=12.3
    - stage: chefspec
      script: bundle exec rake chefspec
      env: CHEF_VERSION=12.14
    - stage: chefspec
      script: bundle exec rake chefspec
      env: CHEF_VERSION=13.8
      rvm: 2.5
    - stage: chefspec
      script: bundle exec rake chefspec
      env: CHEF_VERSION=14
      rvm: 2.5
    - stage: kitchen
      env: KITCHEN_PLATFORM=debian-stretch
      script: bundle exec kitchen test $KITCHEN_PLATFORM
    - env: KITCHEN_PLATFORM=debian-jessie
      script: bundle exec kitchen test $KITCHEN_PLATFORM
    - env: KITCHEN_PLATFORM=debian-buster
      script: bundle exec kitchen test $KITCHEN_PLATFORM
    - env: KITCHEN_PLATFORM=debian-wheezy
      script: bundle exec kitchen test $KITCHEN_PLATFORM
    - env: KITCHEN_PLATFORM=ubuntu-18.04
      script: bundle exec kitchen test $KITCHEN_PLATFORM
    - env: KITCHEN_PLATFORM=centos-7
      script: bundle exec kitchen test $KITCHEN_PLATFORM
  allow_failures:
    - env: CHEF_VERSION=14
    - env: CHEF_VERSION=13.8
    - env: KITCHEN_PLATFORM=centos-7
    - stage: test
