language: ruby

sudo: required
dist: trusty

services: docker

bundler_args: --without plugins

rvm:
  - 2.3

gemfile:
  # - gemfiles/Gemfile.jessie
  - Gemfile

env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.docker.yml
  matrix:
    - CHEF_VERSION=12.0.3
    - CHEF_VERSION=12.14.60
    - CHEF_VERSION=

script:
  - bundle exec rake --tasks
  - bundle exec rake rubocop
  - bundle exec rake foodcritic
  - bundle exec rake chefspec
  - bundle exec rake kitchen:all
