---
language: ruby
cache: bundler

# dist: xenial

services: docker

# bundler in the travis image is too old:
before_install:
  - gem install bundler

bundler_args: --without vagrant

before_script:
  # integration test for sys::autofs will start automounter
  #  this will fail inside docker container because autofs4 cannot be loaded
  #  pre-loading autofs4 on the host fixes this issue
  - sudo modprobe autofs4
  - bundle exec kitchen list

env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.docker.yml
  jobs:
    - KITCHEN_PLATFORM=debian-stretch
    - KITCHEN_PLATFORM=debian-buster
    - KITCHEN_PLATFORM=debian-bullseye
    - KITCHEN_PLATFORM=debian-jessie
    - KITCHEN_PLATFORM=debian-wheezy
    - KITCHEN_PLATFORM=ubuntu-18.04
    - KITCHEN_PLATFORM=centos-7
    - KITCHEN_SUITE=accounts
    - KITCHEN_SUITE=apt
    - KITCHEN_SUITE=autofs
    - KITCHEN_SUITE=banner
    - KITCHEN_SUITE=chef
    - KITCHEN_SUITE=mail
    - KITCHEN_SUITE=ssh
    - KITCHEN_SUITE=mail

rvm:
# - system # does not work with `gem install bundler`
  - 2.3
  - 2.5
# - 2.1
#     before_install:
#        - gem install bundler -v ‘< 2’

stages:
  - rubocop
  - foodcritic
  - chefspec
  - kitchen

jobs:
  fast_finish: true
  include:
    - stage: rubocop
      script: bundle exec rake rubocop
    - stage: foodcritic
      script: bundle exec rake foodcritic
    - stage: chefspec
      script: bundle exec rake chefspec
      env: CHEF_VERSION=12.3
    - stage: chefspec
      script: bundle exec rake chefspec
      env: CHEF_VERSION=12.14
    - stage: chefspec
      script: bundle exec rake chefspec
      env: CHEF_VERSION=13.8
      rvm: 2.5
    - stage: chefspec
      script: bundle exec rake chefspec
      env: CHEF_VERSION=14
      rvm: 2.5
    - stage: chefspec
      script: bundle exec rake chefspec
      env: CHEF_VERSION=15
      rvm: 2.5
    - stage: kitchen
      script: bundle exec kitchen test $KITCHEN_SUITE-$KITCHEN_PLATFORM
  allow_failures:
    - env: CHEF_VERSION=15
    - env: CHEF_VERSION=14
    - env: CHEF_VERSION=13.8
    - env: KITCHEN_PLATFORM=centos-7
    # bundler fails to install amd breaks verify on Jessie:
    - env: KITCHEN_PLATFORM=debian-jessie
    # has a broken sources.list:
    - env: KITCHEN_PLATFORM=debian-wheezy
    - stage: test
