language: ruby

sudo: required
dist: trusty

services: docker

bundler_args: --without plugins

gemfile:
  - gemfiles/Gemfile.jessie
  - Gemfile

env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.docker.yml

script:
  - bundle exec rake --tasks
  - bundle exec rake rubocop
  - bundle exec rake foodcritic
  - bundle exec rake chefspec
  - bundle exec rake kitchen:all
