language: ruby
cache: bundler

sudo: required
dist: trusty

services: docker

# bundler in the travis image is too old:
before_install:
    - gem install bundler

bundler_args: --without plugins

install:
  # chefspec requires that the repo is checked out to a dir
  #  named like the cookbook name, therefore we check it out again
  #  cf. https://stackoverflow.com/questions/32580821/
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git sys
  - cd sys
  - git checkout -qf $TRAVIS_COMMIT
  - bundle install --without plugins

rvm:
  - 2.1.5
  - 2.3.1
  - ruby-head

env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.docker.yml
  - CHEF_VERSION=14
  - CHEF_VERSION=13
  - CHEF_VERSION=12.14.60
  - CHEF_VERSION=12.3.0
  - CHEF_VERSION=12.0.3

jobs:
  include:
    - stage: rubocop
      script: bundle exec rake rubocop
    - stage: foodcritic
      script: bundle exec rake foodcritic
    - stage: chefspec
      script: bundle exec rake chefspec
    - stage: kitchen
      script: bundle exec rake kitchen:all
