---
language: ruby
cache: bundler

sudo: required
dist: trusty

services: docker

# bundler in the travis image is too old:
before_install:
  - gem install bundler

bundler_args: --without plugins

install:
  # chefspec requires that the repo is checked out to a dir
  #  named like the cookbook name, therefore we check it out again
  #  cf. https://stackoverflow.com/questions/32580821/
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git sys
  - cd sys
  - git checkout -qf $TRAVIS_COMMIT
  - bundle install --without plugins

rvm:
  - 2.2
  - 2.3.3
  - 2.4
  - 2.5
  - ruby-head

env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.docker.yml
  matrix:
    - CHEF_VERSION=14.1
    - CHEF_VERSION=13
    - CHEF_VERSION=12.14.60
    - CHEF_VERSION=12.3.0
    - CHEF_VERSION=12.0.3

matrix:
  exclude:
    - rvm: 2.3.3
      env: CHEF_VERSION=14.1

stages:
  - rubocop
  - foodcritic
  - test
  - kitchen

jobs:
  include:
    - script: bundle exec rake rubocop
    - script: bundle exec rake foodcritic
    - script: bundle exec rake chefspec
    - script: bundle exec rake kitchen:all
