language: ruby

sudo: required
dist: trusty

services: docker

bundler_args: --without plugins

env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.docker.yml

matrix:
  include:
    - env: CHEF_VERSION=master
      rvm: ruby-head
    - env: CHEF_VERSION=12.14.60
      rvm: 2.3.1
    - env: CHEF_VERSION=12.3.0
      rvm: 2.1.5
    - env: CHEF_VERSION=12.0.3
      rvm: 2.1.5

script:
  - bundle exec rake --tasks
  - bundle exec rake rubocop
  - bundle exec rake foodcritic
  - bundle exec rake chefspec
  - bundle exec rake kitchen:all
