source 'http://rubygems.org'

gem 'chef-zero'

group :jessie do
  # net-ssh >= 5 requires ruby 2.2 and
  # net-telnet >= 0.2 requires ruby 2.3
  if Gem::Version.new(RUBY_VERSION.dup) < Gem::Version.new('2.2.0')
    gem 'net-ssh',    '< 5'
    gem 'net-telnet', '< 0.2'
  end
end
